countries = ['france', 'japan', 'south korea', 'canada', 'new zealand']
print("\nHere's the number of countries in the list")
print(len(countries))
print("\nHere's the sorted list of the countries")
print(sorted(countries))
print("\nHere's the reversed sorted list of the countries")
countries.reverse()
print(countries)
countries.sort()
countries.sort(reverse=True)
print("\nHere's the alphabetically reversed sorted list of the countries")
print(countries)
